// Daftar pertanyaan untuk kuis
const PERTANYAAN = [
  {q: 'Ibu kota Indonesia adalah?', a: ['Jakarta','Bandung','Surabaya','Medan'], correct:0},
  {q: 'Bendera Indonesia terdiri dari warna?', a: ['Merah dan Putih','Merah dan Biru','Putih dan Hijau','Biru dan Kuning'], correct:0},
  {q: 'Planet terbesar di tata surya?', a: ['Bumi','Mars','Jupiter','Saturnus'], correct:2},
  {q: 'Laut terbesar di dunia?', a: ['Laut Jawa','Samudra Pasifik','Samudra Hindia','Laut Cina Selatan'], correct:1},
  {q: 'Gunung tertinggi di dunia?', a: ['Kilimanjaro','Everest','Elbrus','Denali'], correct:1},
  {q: 'Siapa penemu bola lampu?', a: ['Nikola Tesla','Thomas Edison','Alexander Graham Bell','Albert Einstein'], correct:1},
  {q: 'Hewan darat tercepat?', a: ['Singa','Kuda','Cheetah','Rusa'], correct:2},
  {q: 'Bahasa resmi di Brazil?', a: ['Spanyol','Portugis','Inggris','Prancis'], correct:1},
  {q: 'Jumlah provinsi di Indonesia (2025)?', a: ['34','36','38','40'], correct:2},
  {q: 'Pulau terbesar di dunia?', a: ['Kalimantan','Papua','Greenland','Madagaskar'], correct:2},
  {q: 'Lambang kimia untuk air?', a: ['H2O','O2','CO2','NaCl'], correct:0},
  {q: 'Siapa presiden pertama Indonesia?', a: ['Soekarno','Soeharto','BJ Habibie','Megawati'], correct:0},
  {q: 'Hewan nasional Australia?', a: ['Koala','Kanguru','Emu','Platipus'], correct:1},
  {q: 'Negara dengan populasi terbanyak?', a: ['India','Tiongkok','Amerika Serikat','Indonesia'], correct:0},
  {q: 'Sungai terpanjang di dunia?', a: ['Nil','Amazon','Yangtze','Mississippi'], correct:1},
  {q: 'Ibukota Jepang?', a: ['Kyoto','Tokyo','Osaka','Nagoya'], correct:1},
  {q: 'Penemu telepon?', a: ['Alexander Graham Bell','Thomas Edison','James Watt','Michael Faraday'], correct:0},
  {q: 'Negara penghasil kopi terbesar?', a: ['Brasil','Vietnam','Kolombia','Ethiopia'], correct:0},
  {q: 'Benua yang dijuluki benua hitam?', a: ['Asia','Afrika','Eropa','Australia'], correct:1},
  {q: 'Siapa penulis Harry Potter?', a: ['J.K. Rowling','Suzanne Collins','Stephen King','George R.R. Martin'], correct:0},
  {q: 'Logam cair pada suhu kamar?', a: ['Besi','Merkuri','Timbal','Emas'], correct:1},
  {q: 'Negara asal pizza?', a: ['Prancis','Italia','Spanyol','Yunani'], correct:1},
  {q: 'Planet terdekat dari matahari?', a: ['Merkurius','Venus','Bumi','Mars'], correct:0},
  {q: 'Gunung tertinggi di Indonesia?', a: ['Kerinci','Rinjani','Cartenz Pyramid','Semeru'], correct:2},
  {q: 'Bentuk bumi?', a: ['Datar','Bulat','Kubus','Silinder'], correct:1},
  {q: 'Lambang kimia emas?', a: ['Ag','Au','Fe','Pb'], correct:1},
  {q: 'Negara dengan menara Eiffel?', a: ['Italia','Spanyol','Prancis','Belgia'], correct:2},
  {q: 'Organ yang memompa darah?', a: ['Paru-paru','Otak','Jantung','Ginjal'], correct:2},
  {q: 'Pulau Dewata adalah sebutan untuk?', a: ['Bali','Lombok','Sumatra','Sulawesi'], correct:0},
  {q: 'Mata uang Jepang?', a: ['Yen','Won','Baht','Ringgit'], correct:0},
];